My Project: Door Class Reference
Door Class Reference
#include <Door.h>
Public Member Functions
Door (RoomManager *rm, Room *first, Room *second)
void open ()
void close ()
Private Attributes
RoomManager * rm
Room * first
Room * second
Detailed Description
Definition at line 10 of file Door.h.
Constructor & Destructor Documentation
Door()
Door::Door (RoomManager * rm, Room * first, Room * second)
Definition at line 5 of file Door.cpp.
Member Function Documentation
close()
void Door::close ()
Definition at line 15 of file Door.cpp.
References first, Room::getConnectedRooms(), RoomManager::removeConnection(), rm, and second.
Referenced by SecurityRoom::closeLeftDoor(), and SecurityRoom::closeRightDoor().
open()
void Door::open ()
Definition at line 8 of file Door.cpp.
References RoomManager::addConnection(), first, Room::getConnectedRooms(), rm, and second.
Referenced by SecurityRoom::openLeftDoor(), and SecurityRoom::openRightDoor().
Member Data Documentation
first
Room* Door::first private
Definition at line 13 of file Door.h.
Referenced by close(), and open().
rm
RoomManager* Door::rm private
Definition at line 12 of file Door.h.
Referenced by close(), and open().
second
Room* Door::second private
Definition at line 14 of file Door.h.
Referenced by close(), and open().
The documentation for this class was generated from the following files:
include/Door.h
src/Door.cpp