My Project: AnimatronicManager Class Reference
AnimatronicManager Class Reference
#include <AnimatronicManager.h>
Public Member Functions
AnimatronicManager (MoveManager *mm, RoomManager *rm, int night)
void createAnimatronic (std::string name)
std::unordered_set< Animatronic * > getAllAnimatronics ()
~AnimatronicManager ()
Private Attributes
std::unordered_set< Animatronic * > all_animatronics
MoveManager * mm
RoomManager * rm
int night
DBworker * dbworker
Detailed Description
Definition at line 18 of file AnimatronicManager.h.
Constructor & Destructor Documentation
AnimatronicManager()
AnimatronicManager::AnimatronicManager (MoveManager * mm, RoomManager * rm, int night)
Definition at line 16 of file AnimatronicManager.cpp.
References createAnimatronic().
~AnimatronicManager()
AnimatronicManager::~AnimatronicManager ()
Definition at line 57 of file AnimatronicManager.cpp.
References all_animatronics, and dbworker.
Member Function Documentation
createAnimatronic()
void AnimatronicManager::createAnimatronic (std::string name)
Definition at line 23 of file AnimatronicManager.cpp.
References MoveManager::addAnimatronic(), Room::addAnimatronic(), all_animatronics, dbworker, DBworker::getAnimatronicActivity(), DBworker::getAnimatronicStartRoom(), RoomManager::getRoom(), mm, night, and rm.
Referenced by AnimatronicManager().
getAllAnimatronics()
std::unordered_set<Animatronic*> AnimatronicManager::getAllAnimatronics () inline
Definition at line 31 of file AnimatronicManager.h.
References all_animatronics.
Member Data Documentation
all_animatronics
std::unordered_set<Animatronic*> AnimatronicManager::all_animatronics private
Definition at line 20 of file AnimatronicManager.h.
Referenced by createAnimatronic(), getAllAnimatronics(), and ~AnimatronicManager().
dbworker
DBworker* AnimatronicManager::dbworker private
Definition at line 24 of file AnimatronicManager.h.
Referenced by createAnimatronic(), and ~AnimatronicManager().
mm
MoveManager* AnimatronicManager::mm private
Definition at line 21 of file AnimatronicManager.h.
Referenced by createAnimatronic().
night
int AnimatronicManager::night private
Definition at line 23 of file AnimatronicManager.h.
Referenced by createAnimatronic().
rm
RoomManager* AnimatronicManager::rm private
Definition at line 22 of file AnimatronicManager.h.
Referenced by createAnimatronic().
The documentation for this class was generated from the following files:
include/AnimatronicManager.h
src/AnimatronicManager.cpp