My Project: Room Class Reference
Room Class Reference
#include <Room.h>
Public Member Functions
Room (const std::string &roomName)
virtual ~Room ()=default
std::string getName ()
void addAnimatronic (Animatronic *anim)
void removeAnimatronic (Animatronic *anim)
std::unordered_set< Animatronic * > getAnimatronics ()
void addRoom (Room *room)
void removeRoom (Room *room)
std::unordered_set< Room * > getConnectedRooms ()
Protected Attributes
std::string name
std::unordered_set< Room * > connectedRooms
std::unordered_set< Animatronic * > animatronics
Detailed Description
Definition at line 10 of file Room.h.
Constructor & Destructor Documentation
Room()
Room::Room (const std::string & roomName)
Definition at line 4 of file Room.cpp.
~Room()
virtual Room::~Room () virtual default
Member Function Documentation
addAnimatronic()
void Room::addAnimatronic (Animatronic * anim)
Definition at line 6 of file Room.cpp.
References animatronics.
Referenced by AnimatronicManager::createAnimatronic(), and MoveManager::transition().
addRoom()
void Room::addRoom (Room * room)
Definition at line 22 of file Room.cpp.
References connectedRooms.
Referenced by RoomManager::addConnection(), and TEST().
getAnimatronics()
std::unordered_set< Animatronic * > Room::getAnimatronics ()
Definition at line 18 of file Room.cpp.
References animatronics.
Referenced by Core::leftDoorOutput(), Core::rightDoorOutput(), and Player::update().
getConnectedRooms()
std::unordered_set< Room * > Room::getConnectedRooms ()
Definition at line 34 of file Room.cpp.
References connectedRooms.
Referenced by Animatronic::ai(), Bonnie::ai(), Chica::ai(), Foxy::ai(), Freddy::ai(), G_Freddy::ai(), Door::close(), Door::open(), and TEST().
getName()
std::string Room::getName () inline
Definition at line 19 of file Room.h.
References name.
Referenced by Bonnie::ai(), and Foxy::ai().
removeAnimatronic()
void Room::removeAnimatronic (Animatronic * anim)
Definition at line 12 of file Room.cpp.
References animatronics.
Referenced by MoveManager::transition().
removeRoom()
void Room::removeRoom (Room * room)
Definition at line 28 of file Room.cpp.
References connectedRooms.
Referenced by RoomManager::removeConnection().
Member Data Documentation
animatronics
std::unordered_set<Animatronic*> Room::animatronics protected
Definition at line 14 of file Room.h.
Referenced by addAnimatronic(), getAnimatronics(), and removeAnimatronic().
connectedRooms
std::unordered_set<Room*> Room::connectedRooms protected
Definition at line 13 of file Room.h.
Referenced by addRoom(), getConnectedRooms(), and removeRoom().
name
std::string Room::name protected
Definition at line 12 of file Room.h.
Referenced by getName().
The documentation for this class was generated from the following files:
include/Room.h
src/Room.cpp