My Project: SecurityRoom Class Reference
SecurityRoom Class Reference
#include <SecurityRoom.h>
Public Member Functions
SecurityRoom (const std::string &roomName, Room *left, Room *right, RoomManager *rm)
void closeLeftDoor ()
void openLeftDoor ()
void closeRightDoor ()
void openRightDoor ()
~SecurityRoom ()
Public Member Functions inherited from Room
Room (const std::string &roomName)
virtual ~Room ()=default
std::string getName ()
void addAnimatronic (Animatronic *anim)
void removeAnimatronic (Animatronic *anim)
std::unordered_set< Animatronic * > getAnimatronics ()
void addRoom (Room *room)
void removeRoom (Room *room)
std::unordered_set< Room * > getConnectedRooms ()
Private Attributes
Door * leftDoor
Door * rightDoor
Additional Inherited Members
Protected Attributes inherited from Room
std::string name
std::unordered_set< Room * > connectedRooms
std::unordered_set< Animatronic * > animatronics
Detailed Description
Definition at line 9 of file SecurityRoom.h.
Constructor & Destructor Documentation
SecurityRoom()
SecurityRoom::SecurityRoom (const std::string & roomName, Room * left, Room * right, RoomManager * rm) inline
Definition at line 14 of file SecurityRoom.h.
References leftDoor, and rightDoor.
~SecurityRoom()
SecurityRoom::~SecurityRoom () inline
Definition at line 22 of file SecurityRoom.h.
References leftDoor, and rightDoor.
Member Function Documentation
closeLeftDoor()
void SecurityRoom::closeLeftDoor () inline
Definition at line 18 of file SecurityRoom.h.
References Door::close(), and leftDoor.
Referenced by Player::updateDoor().
closeRightDoor()
void SecurityRoom::closeRightDoor () inline
Definition at line 20 of file SecurityRoom.h.
References Door::close(), and rightDoor.
Referenced by Player::updateDoor().
openLeftDoor()
void SecurityRoom::openLeftDoor () inline
Definition at line 19 of file SecurityRoom.h.
References leftDoor, and Door::open().
Referenced by Player::update(), and Player::updateDoor().
openRightDoor()
void SecurityRoom::openRightDoor () inline
Definition at line 21 of file SecurityRoom.h.
References Door::open(), and rightDoor.
Referenced by Player::update(), and Player::updateDoor().
Member Data Documentation
leftDoor
Door* SecurityRoom::leftDoor private
Definition at line 11 of file SecurityRoom.h.
Referenced by closeLeftDoor(), openLeftDoor(), SecurityRoom(), and ~SecurityRoom().
rightDoor
Door* SecurityRoom::rightDoor private
Definition at line 12 of file SecurityRoom.h.
Referenced by closeRightDoor(), openRightDoor(), SecurityRoom(), and ~SecurityRoom().
The documentation for this class was generated from the following file:
include/SecurityRoom.h