My Project: Animatronic Class Reference
Animatronic Class Reference
#include <Animatronic.h>
Public Member Functions
Animatronic (const std::string &name, Room *start_room, int cooldown)
std::string getName ()
Room * where ()
void update (MoveManager *mm)
virtual void move (MoveManager *mm)
virtual Room * ai ()
virtual ~Animatronic ()=default
Protected Attributes
std::string name
Room * current_room
unsigned int max_cooldown
unsigned int remaining_cooldown
Detailed Description
Definition at line 10 of file Animatronic.h.
Constructor & Destructor Documentation
Animatronic()
Animatronic::Animatronic (const std::string & name, Room * start_room, int cooldown)
Definition at line 8 of file Animatronic.cpp.
~Animatronic()
virtual Animatronic::~Animatronic () virtual default
Member Function Documentation
ai()
Room * Animatronic::ai () virtual
Reimplemented in G_Freddy, Freddy, Foxy, Chica, and Bonnie.
Definition at line 30 of file Animatronic.cpp.
References current_room, and Room::getConnectedRooms().
Referenced by move().
getName()
std::string Animatronic::getName () inline
Definition at line 18 of file Animatronic.h.
References name.
move()
void Animatronic::move (MoveManager * mm) virtual
Reimplemented in Foxy.
Definition at line 19 of file Animatronic.cpp.
References ai(), current_room, max_cooldown, remaining_cooldown, MoveManager::transition(), and where().
Referenced by update().
update()
void Animatronic::update (MoveManager * mm)
Definition at line 10 of file Animatronic.cpp.
References move(), and remaining_cooldown.
where()
Room* Animatronic::where () inline
Definition at line 19 of file Animatronic.h.
References current_room.
Referenced by move(), and Foxy::move().
Member Data Documentation
current_room
Room* Animatronic::current_room protected
Definition at line 13 of file Animatronic.h.
Referenced by ai(), Bonnie::ai(), Chica::ai(), Foxy::ai(), Freddy::ai(), G_Freddy::ai(), move(), Foxy::move(), and where().
max_cooldown
unsigned int Animatronic::max_cooldown protected
Definition at line 14 of file Animatronic.h.
Referenced by Foxy::ai(), and move().
name
std::string Animatronic::name protected
Definition at line 12 of file Animatronic.h.
Referenced by getName().
remaining_cooldown
unsigned int Animatronic::remaining_cooldown protected
Definition at line 15 of file Animatronic.h.
Referenced by Foxy::ai(), move(), and update().
The documentation for this class was generated from the following files:
include/Animatronic.h
src/Animatronic.cpp