My Project: RoomManager Class Reference
RoomManager Class Reference
#include <RoomManager.h>
Public Member Functions
RoomManager ()
void addConnection (Room *r1, Room *r2)
void removeConnection (Room *r1, Room *r2)
Room * getRoom (std::string name)
std::unordered_set< Room * > getAllRooms ()
~RoomManager ()
Private Attributes
std::unordered_set< Room * > all_rooms
Detailed Description
Definition at line 9 of file RoomManager.h.
Constructor & Destructor Documentation
RoomManager()
RoomManager::RoomManager ()
Definition at line 8 of file RoomManager.cpp.
References addConnection(), and all_rooms.
~RoomManager()
RoomManager::~RoomManager ()
Definition at line 82 of file RoomManager.cpp.
References all_rooms.
Member Function Documentation
addConnection()
void RoomManager::addConnection (Room * r1, Room * r2)
Definition at line 60 of file RoomManager.cpp.
References Room::addRoom().
Referenced by Door::open(), and RoomManager().
getAllRooms()
std::unordered_set<Room*> RoomManager::getAllRooms () inline
Definition at line 17 of file RoomManager.h.
References all_rooms.
Referenced by Core::cheatOutput().
getRoom()
Room * RoomManager::getRoom (std::string name)
Definition at line 71 of file RoomManager.cpp.
References all_rooms.
Referenced by Core::camOutput(), and AnimatronicManager::createAnimatronic().
removeConnection()
void RoomManager::removeConnection (Room * r1, Room * r2)
Definition at line 65 of file RoomManager.cpp.
References Room::removeRoom().
Referenced by Door::close().
Member Data Documentation
all_rooms
std::unordered_set<Room*> RoomManager::all_rooms private
Definition at line 11 of file RoomManager.h.
Referenced by getAllRooms(), getRoom(), RoomManager(), and ~RoomManager().
The documentation for this class was generated from the following files:
include/RoomManager.h
src/RoomManager.cpp