My Project: Foxy Class Reference
Foxy Class Reference
#include <Foxy.h>
Public Member Functions
Foxy (const std::string &animatronicName, Room *start_room, int cooldown)
void move (MoveManager *mm) override
Room * ai () override
Public Member Functions inherited from Animatronic
Animatronic (const std::string &name, Room *start_room, int cooldown)
std::string getName ()
Room * where ()
void update (MoveManager *mm)
virtual ~Animatronic ()=default
Private Attributes
std::vector< std::string > foxy_path = {"1C", "2A", "2B", "left", "Security Room"}
Room * start_room
Additional Inherited Members
Protected Attributes inherited from Animatronic
std::string name
Room * current_room
unsigned int max_cooldown
unsigned int remaining_cooldown
Detailed Description
Definition at line 7 of file Foxy.h.
Constructor & Destructor Documentation
Foxy()
Foxy::Foxy (const std::string & animatronicName, Room * start_room, int cooldown) inline
Definition at line 12 of file Foxy.h.
Member Function Documentation
ai()
Room * Foxy::ai () override virtual
Reimplemented from Animatronic.
Definition at line 20 of file Foxy.cpp.
References Animatronic::current_room, foxy_path, Room::getConnectedRooms(), Room::getName(), Animatronic::max_cooldown, Animatronic::remaining_cooldown, and start_room.
Referenced by move().
move()
void Foxy::move (MoveManager * mm) override virtual
Reimplemented from Animatronic.
Definition at line 11 of file Foxy.cpp.
References ai(), Animatronic::current_room, MoveManager::transition(), and Animatronic::where().
Member Data Documentation
foxy_path
std::vector<std::string> Foxy::foxy_path = {"1C", "2A", "2B", "left", "Security Room"} private
Definition at line 9 of file Foxy.h.
Referenced by ai().
start_room
Room* Foxy::start_room private
Definition at line 10 of file Foxy.h.
Referenced by ai().
The documentation for this class was generated from the following files:
include/Foxy.h
src/Foxy.cpp