My Project: Core Class Reference
Core Class Reference
#include <Core.h>
Public Member Functions
Core (MoveManager *mm, RoomManager *rm, Player *p)
void run ()
void stop ()
void handleInput (char key)
bool getStatus ()
void death ()
Private Member Functions
void update ()
void cheatOutput ()
void leftDoorOutput ()
void rightDoorOutput ()
void camOutput ()
Private Attributes
MoveManager * mm
RoomManager * rm
Room * left
Room * right
Room * currentRoom
Player * p
bool isRunning
int tickCount
bool cheat
Detailed Description
Definition at line 10 of file Core.h.
Constructor & Destructor Documentation
Core()
Core::Core (MoveManager * mm, RoomManager * rm, Player * p)
Definition at line 10 of file Core.cpp.
Member Function Documentation
camOutput()
void Core::camOutput () private
Definition at line 120 of file Core.cpp.
References currentRoom, RoomManager::getRoom(), and rm.
Referenced by update().
cheatOutput()
void Core::cheatOutput () private
Definition at line 43 of file Core.cpp.
References RoomManager::getAllRooms(), and rm.
Referenced by update().
death()
void Core::death ()
Definition at line 128 of file Core.cpp.
Referenced by update().
getStatus()
bool Core::getStatus () inline
Definition at line 33 of file Core.h.
References isRunning.
handleInput()
void Core::handleInput (char key)
Definition at line 74 of file Core.cpp.
leftDoorOutput()
void Core::leftDoorOutput () private
Definition at line 53 of file Core.cpp.
References Room::getAnimatronics(), and left.
Referenced by update().
rightDoorOutput()
void Core::rightDoorOutput () private
Definition at line 61 of file Core.cpp.
References Room::getAnimatronics(), and right.
Referenced by update().
run()
void Core::run ()
Definition at line 12 of file Core.cpp.
References isRunning, TICK_DURATION(), and update().
stop()
void Core::stop ()
Definition at line 69 of file Core.cpp.
References isRunning.
Referenced by update().
update()
void Core::update () private
Definition at line 20 of file Core.cpp.
References camOutput(), cheat, cheatOutput(), death(), Player::energyCheck(), Player::isAlive(), leftDoorOutput(), Player::leftDoorStatus(), Player::leftLightStatus(), mm, p, rightDoorOutput(), Player::rightDoorStatus(), Player::rightLightStatus(), stop(), tickCount, MoveManager::update(), and Player::update().
Referenced by run().
Member Data Documentation
cheat
bool Core::cheat private
Definition at line 20 of file Core.h.
Referenced by update().
currentRoom
Room* Core::currentRoom private
Definition at line 16 of file Core.h.
Referenced by camOutput().
isRunning
bool Core::isRunning private
Definition at line 18 of file Core.h.
Referenced by getStatus(), run(), and stop().
left
Room* Core::left private
Definition at line 14 of file Core.h.
Referenced by leftDoorOutput().
mm
MoveManager* Core::mm private
Definition at line 12 of file Core.h.
Referenced by update().
p
Player* Core::p private
Definition at line 17 of file Core.h.
Referenced by update().
right
Room* Core::right private
Definition at line 15 of file Core.h.
Referenced by rightDoorOutput().
rm
RoomManager* Core::rm private
Definition at line 13 of file Core.h.
Referenced by camOutput(), and cheatOutput().
tickCount
int Core::tickCount private
Definition at line 19 of file Core.h.
Referenced by update().
The documentation for this class was generated from the following files:
include/Core.h
src/Core.cpp