My Project: MoveManager Class Reference
MoveManager Class Reference
#include <MoveManager.h>
Public Member Functions
void update ()
void addAnimatronic (Animatronic *)
void transition (Animatronic *animatronic, Room *current_room, Room *new_room)
Private Attributes
std::unordered_set< Animatronic * > animatronics
Detailed Description
Definition at line 13 of file MoveManager.h.
Member Function Documentation
addAnimatronic()
void MoveManager::addAnimatronic (Animatronic * animatronic)
Definition at line 7 of file MoveManager.cpp.
References animatronics.
Referenced by AnimatronicManager::createAnimatronic().
transition()
void MoveManager::transition (Animatronic * animatronic, Room * current_room, Room * new_room)
Definition at line 18 of file MoveManager.cpp.
References Room::addAnimatronic(), and Room::removeAnimatronic().
Referenced by Animatronic::move(), and Foxy::move().
update()
void MoveManager::update ()
Definition at line 12 of file MoveManager.cpp.
References animatronics.
Referenced by Core::update().
Member Data Documentation
animatronics
std::unordered_set<Animatronic*> MoveManager::animatronics private
Definition at line 15 of file MoveManager.h.
Referenced by addAnimatronic(), and update().
The documentation for this class was generated from the following files:
include/MoveManager.h
src/MoveManager.cpp